name: icalendar_plus
description: "This Dart plugin provides a comprehensive set of classes to create, manage, serialize, and parse iCalendar components. It supports creating events, to-dos, journals, alarms, free/busy times, timezones, and more. The plugin adheres to the iCalendar (`.ics`) format, making it easy to integrate with calendar applications."
version: 0.0.7
homepage: https://github.com/mskayali
repository: https://github.com/mskayali/ICalendarDart
publish_to: https://pub.dev/packages/icalendar_plus

environment:
  sdk: ^3.5.3