name: icalendar
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://spinex.io

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
